// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
public class PE002{

	private final static int MAX = 400000;
	
	public static void main(String args[]){
		int a = 0, b = 2, sum = 2;
		while (a < MAX || b < MAX){
			if (b > a){
				a = 4*b+a;
				sum += a;
			}
			else {
				b = 4*a+b;
				sum += b;
			}
		}
		System.out.println(sum);
	}

}